### ISSUE TITLE
No response from pino-mongodb

### ISSUE THREAD

**Issue by HackyDev** [pinojs/pino-mongodb#13]
- Version: 2.1.2
- OS: Ubuntu 18.04

Hello, sir! Thank you for this awesome tool!
I can't figure out how to make it work.

When I run the following line on Ubuntu 18.04 the terminal cursor moves to the next line and waits for user input. The process never exits. What am I missing?

`echo '{"name": "Viktor"}' | pino-mongodb -u mongodb://127.0.0.1:27017`

Apart from that everything seems to work.

**Comment by viktor-ku** [comment]
Hi, I am not sure what's the problem. Try tweaking the version of the mongodb installed locally or in the program itself.

**Comment by HackyDev** [comment]
Here's another example. 
I created a **JS** script `test.js` that has one line `process.exit(1)`.
When I try to run it `node ./test.js | pino-mongodb -u` nothing happens. The cursor is blinking on the command line until I do `CTRL-C`. The same in `powershell`, `bash`, `cmd`. Is there a way to kill the `pino-mongodb` process from `test.js` script? Any advice?

![1](https://user-images.githubusercontent.com/70698428/103650353-14530b80-4f8a-11eb-8405-110597868362.png)
![2](https://user-images.githubusercontent.com/70698428/103650359-15843880-4f8a-11eb-9409-c804c83811c7.png)

**Comment by HackyDev** [comment]
@viktor-ku, I'd like to propose a new option (--terminator). When a user sends to output a line that matches `--terminator` symbols the program exits. The code below is an approximation of how it would work. Do you think it's a good idead? Would you merge changes if I made a PR?

**pino-mongodb.js**
```
  .option('-t, --terminator', 'symbols to terminate pipe', false) // NEW LINE

  emitter.on('line', (line) => { 
    // NEW CODE ↓
    if (program.terminator && line === program.terminator) { 
        mClient.close(process.exit)
    }
    // ↑
    insert(collection, log(line))
  })
```

**Comment by viktor-ku** [comment]
Not sure if it's a good idea honestly. Because the project uses `carrier` as a dependency, we rely on its logic to listen and handle input lines. As far as I know it stays open forever until you kill it, and because this program should either work as a testing solution or as a all-time running process I don't see a point of actually killing it once, or at some point. Think about it as a web server.

**Comment by Tarrask** [comment]
I think I'm facing the same problem. When the program that pipe logs to pino-mongodb stops, pino-mongodb keep running, waiting for logs on the stdin. I think that pino-mongodb should exits when the stdin is closed, if that is doable.

**Comment by mcollina** [comment]
A PR in this regard would be awesome
