### ISSUE TITLE
mongodb+srv:// links not supported

### ISSUE THREAD

**Issue by msklvsk** [pinojs/pino-mongodb#14]
The underlying `muri` lib doesn’t support Atlas’s `mongodb+srv` links.
Proposal: switch to mongodb node driver's built-in parser like Mongoose did: https://github.com/aheckmann/muri/issues/17.

**Comment by viktor-ku** [comment]
Very good idea, however I will not have time for this in the near few weeks. Feel free to submit a PR. Thank you!

**Comment by quintesse** [comment]
I think this is now supported in v7 (at least it works for me). So this issue can probably be closed.
