### ISSUE TITLE
tests fail on node 6

### ISSUE THREAD

**Issue by davidmarkclements** [pinojs/pino-mongodb#6]
our pino-integration CI is showing a failure on Node 6 for pino-mongodb, because the new release uses the spread operator.

Node 6 is still currently supported since it doesn't reach end-of-life until April 2019

![image](https://user-images.githubusercontent.com/1190716/49242580-6ae4d780-f40b-11e8-8c5a-49c530f1bef7.png)

**Comment by viktor-ku** [comment]
@davidmarkclements fixed in `v2.0.1` just now (https://github.com/pinojs/pino-mongodb/commit/c536efa610990add07e65b27bba025f4a0b143cd)

**Comment by davidmarkclements** [comment]
Awesome 👍
