### ISSUE TITLE
Error when using pipe 

### ISSUE THREAD

**Issue by farynam** [pinojs/pino-mongodb#68]
When running pino-mongodb like echo '{"name": "Viktor"}' | pino-mongodb [options] [mongo-url] I receive error "collection name must be a String". 

in pino-mongodb.js

` 
    const collection = db.collection(program.collection)
  `

should be:
`
    const collection = db.collection(program.opts().collection)
  `

**Comment by mcollina** [comment]
@Eomm could u take a look?
