### ISSUE TITLE
e2e use mongodb-memory-server instead of docker

### ISSUE THREAD

**Issue by climba03003** [pinojs/pino-mongodb#71]
Currently, it use docker image for the e2e test. It is not a bad, but it is hard to run the test locally. For example, I am in Windows environment and using WSL which is hard to use docker.

I would suggest to use [`mongodb-memory-server`](https://www.npmjs.com/package/mongodb-memory-server) which provide a local instance for `mongodb` for testing propose and the environment can be clean for each jobs.

By compare the pros and cons
1. `mongodb-memory-server` need longer time for the startup
2. isolated environment for each job
3. not depends on `docker`

It is open to discussion.

**Comment by mcollina** [comment]
I'm not really happy about that module as it's maintained by just one guy. I think using docker is simpler long term.
