### ISSUE TITLE
Cannot find module 'pino-mongodb'

### ISSUE THREAD

**Issue by amda-phd** [pinojs/pino-mongodb#75]
While trying to save logs from a hapi-based API to a MongoDB, I'm encountering several issues with hapi-pino and pino-mongodb. My goal is to produce a pino-mongodb transport for the hapi-pino stream similar to the transport shown in your example `mongo-transport.js`.
But this is simply not possible as, even after checking that the module is actually installed in my node_modules folder,  `const PinoMongoDB = require("pino-mongodb");` produces `Cannot find module 'pino-mongodb'`. I simply cannot generate the transport or even try to attach it to hapi-pino and I cannot find a solution for that.

- Package version: 3.1.0
- Node.js version: 16.9.0
- Expected behavior: `require("pino-mongodb")` loads module and allows creation of a new transport.
- Actual behavior: The module doesn't get loaded when invoqued.

**Comment by mcollina** [comment]
Can you include a script to reproduce the problem?

**Comment by amda-phd** [comment]
The first lines of my `manifest.js` look like:
```
"use strict";

const PinoMongoDB = require("pino-mongodb");
```

On the same file, I register hapi-pino by:
```
{
      plugin: require("hapi-pino"),
      options: {
        prettyPrint: env !== "prod",
        redact: ["req.headers.authorization"],
        ignoreFunc: (options, request) =>
          request.path.startsWith("/swagger") ||
          request.path.includes("documentation"),
      },
    },
```
Even if I don't try to use PinoMongoDB in any way, this produces `Uncaught Error: Cannot find module 'pino-mongodb'` whenever I try to debug the code.

**Comment by mcollina** [comment]
What's manifest.js? I would recommend you to create a small repro to reproduce.

**Comment by amda-phd** [comment]
Try this:
_package.json_
```
{
  "name": "node-playground",
  "version": "1.0.0",
  "description": "This is my personal Node + JS playground",
  "main": "index.js",
  "scripts": {
    "start": "node index.js",
    "watch": "nodemon index.js"
  },
  "keywords": [
    "node",
    "javascript",
    "playground"
  ],
  "author": "amda",
  "license": "ISC",
  "dependencies": {
    "pino": "^6.13.3",
    "pino-mongodb": "^3.1.0"
  }
}
```
_index.js_
```
"use-strict";

const PinoMongoDB = require("pino-mongodb");

```
And then attempt `npm run start`. You'll see that there's no way to run those two lines:

![image](https://user-images.githubusercontent.com/53900519/135868347-dd6f2e7a-59db-4104-a8aa-229996086a53.png)

**Comment by jsumners** [comment]
I hate `pkg.files` -- https://github.com/pinojs/pino-mongodb/blob/cd4275fe2fc1aa5e07a8712449ad78bc3348ef6e/package.json#L5-L7

Also, missing `main` property.

**Comment by jsumners** [comment]
@mcollina does `main` automatically get pulled in? It's still not listed in the `fils` property.

**Comment by mcollina** [comment]
Yes it does
