### ISSUE TITLE
Logging to multiple collections

### ISSUE THREAD

**Issue by nooreldeensalah** [pinojs/pino-mongodb#89]
Hi,

Is it possible to use this module to log to multiple collections?, the collection can't be changed after registering `pino-mongodb` as a transport to a `pino` instance.

Regards,

**Comment by mcollina** [comment]
I don't understand the usecase. Can you please clarify this?

**Comment by nooreldeensalah** [comment]
I'm running a fastify application that has multiple modules, such as an authentication module, an api module, etc...
I want to be able to select a specific collection to log to, for example upon handling authentication errors then log into `authentication` collection for example, upon server errors, then log to `serverErrors` collection, and so on.

Might be a bit contrived, but that's the scenario I'm trying to achieve.

**Comment by mcollina** [comment]
Unfortunately that's scenario is not currently supported by pino. Your best bet is to either:

1. just use the MongoDB driver directly
2. create a logger for each of your modules, each one with its own transport.

**Comment by mcollina** [comment]
I don't understand the question.

**Comment by nooreldeensalah** [comment]
This question might be more related to fastify, than it is to pino-mongodb, but I want to use both,
The example scenario is, I have routes having a prefix `/login` and routes having a prefix `/payments`
I want to be able to make a separate logger for `/login` routes and another separate one for `/payments`, where each logger has a different transport.

Is this scenario possible using fastify?

**Comment by mcollina** [comment]
> Is this scenario possible using fastify?

I don't think it's possible right now but it could be, there is nothing that prevent this from happening.
